/* eslint-disable */
// Generated by scripts/build-memories-data.ts — do not edit by hand.

export const HERO_CAROUSEL_URLS: readonly string[] = [
  "/hero-carousel/leroy-memorial-main.jpeg",
  "/hero-carousel/dad-012.jpeg",
  "/hero-carousel/IMG_0597.jpeg",
  "/hero-carousel/dad-010.jpeg",
  "/leroy-hero.jpeg",
  "/hero-carousel/dad-013.jpeg",
  "/hero-carousel/dad-005.jpeg",
  "/hero-carousel/dad-007.jpeg",
  "/hero-carousel/dad-008.jpeg",
  "/hero-carousel/dad-003.jpg",
  "/hero-carousel/dad-015.jpeg",
  "/hero-carousel/IMG_0585.jpeg",
  "/hero-carousel/dad-001.jpeg",
  "/hero-carousel/IMG_0600.jpeg",
  "/hero-carousel/dad-016.jpeg",
  "/hero-carousel/dad-004.jpeg",
  "/hero-carousel/IMG_0599.jpeg",
  "/hero-carousel/dad-011.jpeg",
  "/hero-carousel/dad-000.jpeg",
  "/hero-carousel/dad-006.jpeg",
  "/hero-carousel/dad-002.jpeg",
  "/hero-carousel/dad-009.jpeg",
  "/hero-carousel/IMG_0598.jpeg",
  "/hero-carousel/dad-014.jpeg",
];
