/* eslint-disable */
// Generated by scripts/build-memories-data.ts — do not edit by hand.

export const HERO_CAROUSEL_FILES: readonly string[] = [
  "dad-000.jpeg",
  "dad-001.jpeg",
  "dad-002.jpeg",
  "dad-003.jpg",
  "dad-004.jpeg",
  "dad-005.jpeg",
  "dad-006.jpeg",
  "dad-007.jpeg",
  "dad-008.jpeg",
  "dad-009.jpeg",
  "dad-010.jpeg",
  "dad-011.jpeg",
  "dad-012.jpeg",
  "dad-013.jpeg",
  "dad-014.jpeg",
  "dad-015.jpeg",
  "dad-016.jpeg",
];
