/* eslint-disable */
// Generated by scripts/build-memories-data.ts — do not edit by hand.

export const HERO_CAROUSEL_URLS: readonly string[] = [
  "/hero-carousel/IMG_1177.jpeg",
  "/hero-carousel/IMG_1178.jpeg",
  "/hero-carousel/IMG_1179.jpeg",
  "/hero-carousel/IMG_1180.jpeg",
  "/hero-carousel/IMG_1181.jpeg",
  "/hero-carousel/IMG_1182.jpeg",
  "/hero-carousel/IMG_1183.jpeg",
  "/hero-carousel/IMG_1184.jpeg",
  "/hero-carousel/IMG_1185.jpeg",
  "/hero-carousel/IMG_1186.jpeg",
  "/hero-carousel/IMG_1187.jpeg",
  "/hero-carousel/IMG_1188.jpeg",
  "/hero-carousel/IMG_1189.jpeg",
  "/hero-carousel/IMG_1190.jpeg",
  "/hero-carousel/IMG_1191.jpeg",
  "/hero-carousel/IMG_1192.jpeg",
  "/hero-carousel/IMG_1193.jpeg",
  "/hero-carousel/IMG_1194.jpeg",
  "/hero-carousel/IMG_1195.jpeg",
  "/hero-carousel/IMG_1196.jpeg",
  "/hero-carousel/IMG_1197.jpeg",
  "/hero-carousel/IMG_1198.jpeg",
  "/hero-carousel/IMG_1199.jpeg",
];
