/**
 * Prebuild step (runs before `next dev` / `next build`):
 * 1. Writes `public/memories-payload.json` — gallery JSON served from the CDN (no `/api/memories` route).
 * 2. Writes `lib/heroCarouselManifest.generated.ts` — full `/hero-carousel/…` and `/leroy-hero.jpeg` URLs in
 *    display order so `app/page.tsx` never calls `fs.readdir` on `public/hero-carousel` (Next would trace
 *    every hero image into the page bundle). Slides are sorted by IMG number (oldest → newest) for
 *    easy browsing.
 *
 * Usage: npm run build:memories-data
 */

import { mkdir, readdir, writeFile } from "fs/promises";
import { join } from "path";
import { buildMemories } from "../lib/memories";

const payloadPath = join(process.cwd(), "public", "memories-payload.json");
const heroDir = join(process.cwd(), "public", "hero-carousel");
const heroManifestPath = join(
  process.cwd(),
  "lib",
  "heroCarouselManifest.generated.ts",
);

async function listHeroCarouselFiles(): Promise<string[]> {
  try {
    return (await readdir(heroDir))
      .filter(
        (n) =>
          /\.(jpe?g|png|gif|webp)$/i.test(n) && !n.startsWith("."),
      )
      .sort((a, b) => {
        const na = Number(a.match(/IMG_(\d+)/i)?.[1] ?? 0);
        const nb = Number(b.match(/IMG_(\d+)/i)?.[1] ?? 0);
        if (na !== nb) return na - nb;
        return a.localeCompare(b);
      });
  } catch {
    return [];
  }
}

function quoteJsString(s: string): string {
  return JSON.stringify(s);
}

function buildHeroCarouselUrls(heroFiles: string[]): string[] {
  if (heroFiles.length === 0) {
    throw new Error(
      "No images in public/hero-carousel/ — add JPEGs before build.",
    );
  }
  return heroFiles.map((f) => `/hero-carousel/${f}`);
}

async function main() {
  const payload = await buildMemories();
  await mkdir(join(process.cwd(), "public"), { recursive: true });
  const json = JSON.stringify(payload);
  await writeFile(payloadPath, json, "utf8");
  console.log(
    `Wrote ${payloadPath} (${(Buffer.byteLength(json, "utf8") / 1024).toFixed(1)} KB)`,
  );

  const heroFiles = await listHeroCarouselFiles();
  const heroUrls = buildHeroCarouselUrls(heroFiles);
  const ts =
    "/* eslint-disable */\n" +
    "// Generated by scripts/build-memories-data.ts — do not edit by hand.\n\n" +
    "export const HERO_CAROUSEL_URLS: readonly string[] = [\n" +
    heroUrls.map((u) => `  ${quoteJsString(u)},`).join("\n") +
    "\n];\n";
  await writeFile(heroManifestPath, ts, "utf8");
  console.log(
    `Wrote ${heroManifestPath} (${heroUrls.length} hero slide(s), first ${heroFiles[0] ?? "—"})`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
