/**
 * Prebuild step (runs before `next dev` / `next build`):
 * 1. Writes `public/memories-payload.json` — gallery JSON served from the CDN (no `/api/memories` route).
 * 2. Writes `lib/heroCarouselManifest.generated.ts` — filenames only, so `app/page.tsx` never calls
 *    `fs.readdir` on `public/hero-carousel` (Next would otherwise trace every hero image into the page bundle).
 *
 * Usage: npm run build:memories-data
 */

import { mkdir, readdir, writeFile } from "fs/promises";
import { join } from "path";
import { buildMemories } from "../lib/memories";

const payloadPath = join(process.cwd(), "public", "memories-payload.json");
const heroDir = join(process.cwd(), "public", "hero-carousel");
const heroManifestPath = join(
  process.cwd(),
  "lib",
  "heroCarouselManifest.generated.ts",
);

async function listHeroCarouselFiles(): Promise<string[]> {
  try {
    return (await readdir(heroDir))
      .filter(
        (n) =>
          /\.(jpe?g|png|gif|webp)$/i.test(n) && !n.startsWith("."),
      )
      .sort();
  } catch {
    return [];
  }
}

function quoteJsString(s: string): string {
  return JSON.stringify(s);
}

async function main() {
  const payload = await buildMemories();
  await mkdir(join(process.cwd(), "public"), { recursive: true });
  const json = JSON.stringify(payload);
  await writeFile(payloadPath, json, "utf8");
  console.log(
    `Wrote ${payloadPath} (${(Buffer.byteLength(json, "utf8") / 1024).toFixed(1)} KB)`,
  );

  const heroFiles = await listHeroCarouselFiles();
  const ts =
    "/* eslint-disable */\n" +
    "// Generated by scripts/build-memories-data.ts — do not edit by hand.\n\n" +
    "export const HERO_CAROUSEL_FILES: readonly string[] = [\n" +
    heroFiles.map((f) => `  ${quoteJsString(f)},`).join("\n") +
    "\n];\n";
  await writeFile(heroManifestPath, ts, "utf8");
  console.log(`Wrote ${heroManifestPath} (${heroFiles.length} hero image(s))`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
