/**
 * Prebuild step (runs before `next dev` / `next build`):
 * 1. Writes `public/memories-payload.json` — gallery JSON served from the CDN (no `/api/memories` route).
 * 2. Writes `lib/heroCarouselManifest.generated.ts` — full `/hero-carousel/…` and `/leroy-hero.jpeg` URLs in
 *    display order so `app/page.tsx` never calls `fs.readdir` on `public/hero-carousel` (Next would trace
 *    every hero image into the page bundle). First slide is always IMG_0597.jpeg; remainder is
 *    seeded-shuffled (stable for a given set of files; set HERO_CAROUSEL_SHUFFLE_SEED to change order).
 *
 * Usage: npm run build:memories-data
 */

import { mkdir, readdir, writeFile } from "fs/promises";
import { join } from "path";
import { buildMemories } from "../lib/memories";

const payloadPath = join(process.cwd(), "public", "memories-payload.json");
const heroDir = join(process.cwd(), "public", "hero-carousel");
const heroManifestPath = join(
  process.cwd(),
  "lib",
  "heroCarouselManifest.generated.ts",
);

const FIRST_HERO_SLIDE = "leroy-memorial-main.jpeg";
const ROOT_HERO_URL = "/leroy-hero.jpeg";

async function listHeroCarouselFiles(): Promise<string[]> {
  try {
    return (await readdir(heroDir))
      .filter(
        (n) =>
          /\.(jpe?g|png|gif|webp)$/i.test(n) && !n.startsWith("."),
      )
      .sort();
  } catch {
    return [];
  }
}

function quoteJsString(s: string): string {
  return JSON.stringify(s);
}

function seedFromString(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  return () => {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(arr: T[], rng: () => number): void {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j]!, arr[i]!];
  }
}

function buildHeroCarouselUrls(heroFiles: string[]): string[] {
  if (!heroFiles.includes(FIRST_HERO_SLIDE)) {
    throw new Error(
      `Missing public/hero-carousel/${FIRST_HERO_SLIDE} — add it (e.g. copy from Desktop/Pics) before build.`,
    );
  }
  const rest = heroFiles.filter((f) => f !== FIRST_HERO_SLIDE);
  const pool: string[] = [
    ...rest.map((f) => `/hero-carousel/${f}`),
    ROOT_HERO_URL,
  ];
  const seedExtra =
    process.env.HERO_CAROUSEL_SHUFFLE_SEED?.trim() || "leroy-hero-v1";
  const rng = mulberry32(
    seedFromString([...pool].sort().join("|") + "|" + seedExtra),
  );
  shuffleInPlace(pool, rng);
  return [`/hero-carousel/${FIRST_HERO_SLIDE}`, ...pool];
}

async function main() {
  const payload = await buildMemories();
  await mkdir(join(process.cwd(), "public"), { recursive: true });
  const json = JSON.stringify(payload);
  await writeFile(payloadPath, json, "utf8");
  console.log(
    `Wrote ${payloadPath} (${(Buffer.byteLength(json, "utf8") / 1024).toFixed(1)} KB)`,
  );

  const heroFiles = await listHeroCarouselFiles();
  const heroUrls = buildHeroCarouselUrls(heroFiles);
  const ts =
    "/* eslint-disable */\n" +
    "// Generated by scripts/build-memories-data.ts — do not edit by hand.\n\n" +
    "export const HERO_CAROUSEL_URLS: readonly string[] = [\n" +
    heroUrls.map((u) => `  ${quoteJsString(u)},`).join("\n") +
    "\n];\n";
  await writeFile(heroManifestPath, ts, "utf8");
  console.log(
    `Wrote ${heroManifestPath} (${heroUrls.length} hero slide(s), first ${FIRST_HERO_SLIDE})`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
